# App keys
SECRET_TOKEN: '<%= secret_token %>'

development:
  DB_NAME: <%= app_name %>_development
  DB_USER: postgres
  DB_PASSWORD:

test:
  DB_NAME: <%= app_name %>_test
  DB_USER: postgres
  DB_PASSWORD:

production:
  DB_NAME: <%= app_name %>_production
  DB_USER: postgres
  DB_PASSWORD:

# Third party keys
# ...